#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' 

clear
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo "* Installing Dependencies"

sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo "* Installed Dependencies"

echo "* Installing Files"
mkdir -p panel5
cd panel5 || { echo "Failed to change directory to skyport"; exit 1; }
git clone https://github.com/achul123/panel5.git
cd panel5 || { echo "Failed to change directory to panel"; exit 1; }
npm install

echo "* Installed Files"

echo "* Starting Skyport"

npm run seed
npm run createUser

echo "* Starting Skyport With PM2"

sudo npm install -g pm2
pm2 start index.js

echo "* Skyport Installed and Started on Port 3001"

clear
echo "* Made by Faded"
