#!/bin/bash

ascii_art="
 _____         _          _ 
|  ___|_ _  __| | ___  __| |
| |_ / _` |/ _` |/ _ \/ _` |
|  _| (_| | (_| |  __/ (_| |
|_|  \__,_|\__,_|\___|\__,_|
"

ED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' 

clear
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"



echo_message "* Installing Dependencies"

sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

mkdir -p panel5
cd panel5 || { echo_message "Failed to change directory to skyport"; exit 1; }
git clone https://github.com/achul123/panel5.git
cd panel5 || { echo_message "Failed to change directory to panel"; exit 1; }
npm install

echo_message "* Installed Files"

echo_message "* Starting Skyport"

npm run seed
npm run createUser

echo_message "* Starting Skyport With PM2"

sudo npm install -g pm2
pm2 start index.js

clear
echo -e "${CYAN}* Skyport Installed and Started on Port 3001${NC}"
echo "Made by Faded"
